name: Deploy to Oracle Server

on:
  push:
    branches:
      - main # This triggers the robot only when you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and pull code
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            git pull origin main